[package]
name = "m2k"
version = "0.1.0"
authors = ["Andrey Ufimcev <aethe.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
midir = "0.7.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
